use_frameworks!

target 'QQAliyunOSSiOS_Example' do
    pod 'QQAliyunOSSiOS', :git => 'https://github.com/wgqcd/QQAliyunOSSiOS.git'

  target 'QQAliyunOSSiOS_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
